### PR TITLE
Updated reset password request URL on /profile for issue #17

### PR DESCRIPTION
**Pull request by 29parthi**
Updated reset password request URL on /profile for issue #17

### CODE REVIEW

**Comment by 29parthi** [comment]
made 
e7b45e8 changes for #16

**Comment by kimuraz** [comment]
@29parthi Hey, I guess we have some linting error on it, can you check please?

**Comment by 29parthi** [comment]
Sure , I will check that

**Comment by kimuraz** [comment]
hey @29parthi any new on this one? :grimacing:

**Pull request closed without merging**
